### ISSUE TITLE
question: which picom is used? 

### ISSUE THREAD

**Issue by zilahir** [Arian8j2/dotfiles#1]
Hi! 

I am being stuck on the animations of picom for a while now, can't really figure out why they are not working. By wandering around different dotfile repos, it seems like the one's whith picom animations are pretty much the same. That being said, I think the only thing that might be the root cause of this, that some kind of different fork of picom is being used? 

So, could you please tell me which one _you_ are using? 

Thanks in advance!

**Comment by Arian8j2** [comment]
I'm using my own fork of picom, link [here](https://github.com/Arian8j2/picom), But there are other forks that has more complex animation systems such as [dccsillag](https://github.com/dccsillag/picom/tree/implement-window-animations), and [pijulius](https://github.com/pijulius/picom.git) forks.

**Comment by zilahir** [comment]
thanks! appreciate the answer! :)
